In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [5]:
b = np.array([[1,2], [3,4]])

In [6]:
b

array([[1, 2],
       [3, 4]])

In [7]:
print(a.shape, b.shape)

(4,) (2, 2)


In [8]:
c = a.reshape((4,1))

In [9]:
print(c.shape)

(4, 1)


In [12]:
d = a.reshape((2,-1,1))

In [13]:
d.shape

(2, 2, 1)

In [14]:
d

array([[[1],
        [2]],

       [[3],
        [4]]])

In [15]:
a = np.array([1,2,3])
b = np.array([4,5])

c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5])

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b 
c

array([5, 7, 9])

In [17]:
c = np.vstack((a,b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
c = np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [19]:
a

array([1, 2, 3])

In [20]:
mean_a = np.mean(a)
mean_a

2.0

In [21]:
std_a = np.std(a)
std_a

0.816496580927726

In [22]:
norm_a = (a - mean_a) / std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [23]:
np.mean(norm_a)
np.std(norm_a)

0.9999999999999999